.PHONY: gen-frontend
gen-frontend:
	cwgo server --type HTTP --idl ../../idl/frontend/home.proto --service frontend -module github.com/xie628/gomall/app/frontend -I ../../idl -I C:\protoc-29.3-win64\include